# Generated by Django 2.1 on 2022-01-15 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 13, 3, 52, 707856, tzinfo=utc)),
        ),
    ]
